apiVersion: apps/v1
kind: Deployment
metadata:
  name: komp-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komp-ui
  template:
    metadata:
      labels:
        app: komp-ui
    spec:
      containers:
      - name: komp-ui
        image: aido123/komp-ui
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BASE_URL
          value: "https://kompservice.hynes.pri"

---
apiVersion: v1
kind: Service
metadata:
  name: komp-ui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: komp-ui
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: komp-ui
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
      - kompui.hynes.pri
    secretName: tls-secret
  rules:
  - host: kompui.hynes.pri
    http:
      paths:
      - backend:
          serviceName: komp-ui
          servicePort: 80
        path: /(.*)
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlGR1RDQ0F3R2dBd0lCQWdJVU1ObG1PR01VM0prQkJTWWlTN3dRWVE3KzR0Y3dEUVlKS29aSWh2Y05BUUVMDQpCUUF3SERFYU1CZ0dBMVVFQXd3UmEyOXRjSFZwTG1oNWJtVnpMbkJ5YVhZd0hoY05NakF4TVRJM01qRTBPVFF5DQpXaGNOTWpFeE1USTNNakUwT1RReVdqQWNNUm93R0FZRFZRUUREQkZyYjIxd2RXa3VhSGx1WlhNdWNISnBkakNDDQpBaUl3RFFZSktvWklodmNOQVFFQkJRQURnZ0lQQURDQ0Fnb0NnZ0lCQU8yTlNycnpyQ01hYnF0ZVRJZDhoOXR1DQpqZjFsc1JuTUV1WXljclJ0Q0dqRktDNDdpaUs2aEtENGVVSTJVLzVpWEd4U0tPQy92MmtUWjZ2b1d2UFh4UDU5DQp6allsYXJENGZMYjBwT05ub0NtMzlud3BWRnRBOHB2alMzcDFad0ZSRU5MeEpLMHlYVVVhdjBoOFRPRmJzV0FRDQppM3JCUWlVbjd3WGRjTVZ1WW1YVGNOZG5WQ1d4ckFadExaUTBIYkpxNDRFdkNzTHhUMktxRlFpU3pjWnJvTFR3DQpxY1NHOHBtVGd3d1VmWGZGKzRSNjlHV045bUE2dCt0STREcFVkeWZsdFhORWNoNWVEbVVKZjRWSko4elUzSFd6DQpCWTBXcjhsNTNhZ1ZPYjd2TVkrSUN6TnNMWGg0YUJLN2hycGpyOVRtS1Y3bkNSa3p5eVFUNjVQTEhuMmdwblRNDQozZHJpYk9iNnRKSFByUzh0RUlVd3E1alpzL0tpTmNXYy9ZWUtwZlRjWkw2WXVUamRPNmdtRWxBRXQwcTVnalY2DQptTHpEMFUySXpNem82Q1VJVmdlR2hjU2lzUmRZbUdaR1pWZFprTGRpQ2NOK2FIejNhQ2JET0ExZ0p0L09XUnhFDQppMkM4SDd0OEd5RWI5OEUvdzNuU0FwRmpURWxPSENqR0Z5SU1IR0RydTc3b0tlVENIMU1FNEh5UW4rdUZxODkxDQppdUpkb0pLU3BzR0h1NHRVSmlFUW9PUjBjYXZkOHIrYnNoWThTQkw2SjQ3c2VxbklRQ1pDUncrK1duNEFFdU1zDQpUaUNuWnFaOVVxSk44aEJVM0JoUTYwNzRvTVI4ak1CZFNqNE1rRkN2emx5dS9QV2x6eTdQYnlKdXJnUzJlclhxDQpLNWFGV1pSb1BhK1kwV1prbllXTkFnTUJBQUdqVXpCUk1CMEdBMVVkRGdRV0JCUUU1anhzTVQ5blJGekRQbFhFDQp5VXl6cEl0b1pEQWZCZ05WSFNNRUdEQVdnQlFFNWp4c01UOW5SRnpEUGxYRXlVeXpwSXRvWkRBUEJnTlZIUk1CDQpBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUMza0FveFpLaVhGOUt1elN2WUY5akIyQjN0DQpWazRjZDNyUVhNbExlb1Z2VVlVZVI5TnRPR3FhRUY3V0xReEMvSXQwT0h0Y2hPWTVyUkVtZ2xSWEpydFVwb3pBDQovbEhWdkNaVitveHJValBLVWxsM0M1UGRJTGZvTXlnTzh6bkoyTDNzcHpFeGVZT3VsN3pmc09KR1IwRGUreVRJDQpwVXFDd1ljNFlUZm5uQll2OFVFQm1ydDB6em1iR1lBcW0reUFaeHFlUGRSbVo3K3o1cFYvOWdvODBOT2xUc2xMDQpneWZaVUxTRnEyczNnWXdhRzBpNmdTa2ZLa3JKU01YYlcxU1hHeTZkUVlVL2U5eGh6VmdFT2M5NmNTZ1pFWUZNDQpGSUN4WVoyS1NCbVNtOUVjVDZOS1NnS3h5WDBGNWg5cld4NWJoTldDT3UyS3pabldRUzBuNHc0YStuZXY3RzViDQoxTURNNGMxRTFwWk1OaVhSWUpSMWwyaXVUUXlPZVJPc2VvcHVoUEpOeE8vTVRQZS91cUZuZDdPS2wrOGtIVFhhDQo4dVphWWpwYXo3dTlIazEyZ2lUUUZXVS9JaDBFMXZ2R3JQTTJCOTUvOHo0ZTM3ajl6MU4yMStWYVVDS1lIKzQvDQptL3JpajB5cEZ3YVNzV3lOZGEzNGF6Y2J2SVl6MkRoUVVqL3hOL2luMFVMQmdrb2tFZStYaTVZRUVlR1RTY01MDQpEUzBtN01PQ2VxWTBsYTdnYUNOeTRGVzJVcWdnVkdQNjBscXREUTZmZTdMMjVyckNLaVorVXdyR204Ym02QVF0DQoyKytvM3hPbVRyRzdKOUNDVGR0Q0kwcU9PSmN0Z2RBb1hvL3dGM1FLUHhSU2gxdjU3dXB0Y1F6MHhyTnBDMUNHDQp3dENFczJRQllXTHRzV0hZVWc9PQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJSktBSUJBQUtDQWdFQTdZMUt1dk9zSXhwdXExNU1oM3lIMjI2Ti9XV3hHY3dTNWpKeXRHMElhTVVvTGp1Sw0KSXJxRW9QaDVRalpUL21KY2JGSW80TCsvYVJObnEraGE4OWZFL24zT05pVnFzUGg4dHZTazQyZWdLYmYyZkNsVQ0KVzBEeW0rTkxlblZuQVZFUTB2RWtyVEpkUlJxL1NIeE00VnV4WUJDTGVzRkNKU2Z2QmQxd3hXNWlaZE53MTJkVQ0KSmJHc0JtMHRsRFFkc21yamdTOEt3dkZQWXFvVkNKTE54bXVndFBDcHhJYnltWk9EREJSOWQ4WDdoSHIwWlkzMg0KWURxMzYwamdPbFIzSitXMWMwUnlIbDRPWlFsL2hVa256TlRjZGJNRmpSYXZ5WG5kcUJVNXZ1OHhqNGdMTTJ3dA0KZUhob0VydUd1bU92MU9ZcFh1Y0pHVFBMSkJQcms4c2VmYUNtZE16ZDJ1SnM1dnEwa2MrdEx5MFFoVENybU5teg0KOHFJMXhaejloZ3FsOU54a3ZwaTVPTjA3cUNZU1VBUzNTcm1DTlhxWXZNUFJUWWpNek9qb0pRaFdCNGFGeEtLeA0KRjFpWVprWmxWMW1RdDJJSnczNW9mUGRvSnNNNERXQW0zODVaSEVTTFlMd2Z1M3diSVJ2M3dUL0RlZElDa1dOTQ0KU1U0Y0tNWVhJZ3djWU91N3Z1Z3A1TUlmVXdUZ2ZKQ2Y2NFdyejNXSzRsMmdrcEttd1llN2kxUW1JUkNnNUhSeA0KcTkzeXY1dXlGanhJRXZvbmp1eDZxY2hBSmtKSEQ3NWFmZ0FTNHl4T0lLZG1wbjFTb2szeUVGVGNHRkRyVHZpZw0KeEh5TXdGMUtQZ3lRVUsvT1hLNzg5YVhQTHM5dkltNnVCTFo2dGVvcmxvVlpsR2c5cjVqUlptU2RoWTBDQXdFQQ0KQVFLQ0FnQmIwVGZvU05UcEFJZDBIMCt2TXBnRVhaZnVNSWNpZEhsOWxsUTFuc3NZUzlRN0FuSmk5L3JaaVJDOQ0KWWVoWE04ZUxhcm80SElVc1pQNjJPR29uUStmMWdjVFpzdDZwSm5KMStOdGV0aWYyMkE4aWNJc1ZkbVlQa093VQ0KbWhwRkxRTTJ0VlE2eVhPNWlSd1VOVTgxNzg0QVZvVEMzcjNsUktramVETGxiTVFGblpOSS9yeE1rWDd2UVBYVQ0KQ2N6TXNIbmM3Y1RZRXBOZmpHUHkyMk5ENVVmSmlCZm1TVTZ0dzVGc2N1TUlEM01uQXF0Q01YdmdOL0hzdEU5Tw0KM0dUdCsrQ0ZmQmdyMnFqdnJwc21kbDgyMGJPZ25xQnZweXdzMExpM0JmVTY4cE1TYWtBQ0VUY0dFR3dSaVlBSw0KdlFzeVcvL3ptWk12dFpBNEVxY0VpZ2J3QWM4MEtWOTNlWDcvbUxwSlljOUx3NU8yQ2U2aE5VSDVMcTJoWFJqSw0KMlI2MStneG51UGpKbkVINElOazRBTEtRWFVEZDY4S1Q2c0Q5T0oxMXBuOHhjOHkxOUZxck9MS2JIemdYL0FpWg0KbC9UeHp3OFZaSkhhNnlsSnRYSldMSkRaa1RFU0szK2orYXhQa1ZuZWw5SHBNQWlUbnduM09ab1dZdXFMZTZsSQ0KMFE4V2JGdHJ6TmdMZ2VwL2lOWGhCZnY4cE56djVTeXF4Unl3aE10M01mSlhHcjhIZGxYNlBvNnJ6T3BJT1BxMA0KUWw2d24ycmdVaEhYc0RzNEc4N0V0anlLVE9FclUyVWcvZjJZeHg5UEJIcEF3U3RJbUlDUWRvak10bndwa3VXbw0KSmZ1VVhNZnhQVkl5Y2hFaWdXVVVQRFNRSEpzWjBlSW55OWRkcDBUcTlpa0NWWUQwUVFLQ0FRRUEvZ0FWL2VDUg0KU0NmUW9VT2lVUnIvOUdlWDB1ZFBEOFJSaWlsWUsyT2l3MWJuNFErek9rV3lPa1ZXZUNKaU5aR2JnQWN4RGIrdg0KblFhWHRvcG4yKzlOWTBmbDVmaXllbnErd2ZEc3FjT05ST0JETm41OTZQc2JBQy9ZZkNiYmMvSWwzZmRScGJqMQ0KYmw2MzFKdWQwL0lteDdGdERJZTFWYk5hVFJXUlFnTEw3OWErUnhUMm1iaDV4elRaYXEzTGtMdkhyR21WbW9iRw0KT1F6ajVDWlAwejFuT1NCbS91eHdNWjZUYlJENGhmZHN6eVpMWE9yd3dkKzVtZUxoMG9TR005NXA5V3M0NXE1Yw0KYzhvY0c0MWtFUHVSbmZwbUNZUXJ2T2oxVXFuSE1LLzl1WFRZa0tSZUIxMW9SdmdKazlNekYwM2FIVEhJTVowWA0KTW5DSGxDcEMxNGIzZlFLQ0FRRUE3MndPUmpNV0JXYk9BK09CaUExNTNBU0JZRms0eGZkcEhIQXdaa2hESE9Gaw0KM2dwVlhuSHQ3Yzd0UXNmUUFueStDQVpqQUFiaVpQc214cENpWHpRV1l1ZUc2N2RBKzNqZTdhb1lNY0JraEgvQQ0KdmVHU3F0RTFzZk8rMGltU2hEeENteEprUlBwZlJ1N0FNZlhETmZROEVxTjIzdGc1ZlZPbWRjNEhma3Rab0RQZQ0Kbm9Rdmsxc0ZFVzUwc1FIRjRiMTJJbEpZaEpHeEZyVlRESEI4WFQ0enVBUkUyK1drZjdCY0lpWWhvZk9aOS81eQ0KYWVUY0drNlgrNVkxdTdlNWpLUnlzMGRsdWE0VmxDM21pcFpYcnFEZW9BS3llSU5MRnZmOHU2b3ZuU1pkMm1jbw0KeEJmbEQxMThraEgvbTFSS3hldVVFU3d5M1JGVjhQRXV2TzMxUlFuRFVRS0NBUUVBMElmbmhqaFJibWpwdXd3WQ0KL2ZkcHZoRXlyMzhpQkxMTHN0K0F1SmFqY1RZdlJ6SXBsaVRVVDB6UDBlK0FxN1F3Y3lyMFZmSlN6bHMwUVRSZQ0KVWsya1BtY3YwdCtjUUR2MzBxZm0xUFZzVE9qRnBiNnh4bzRwdTd5TVFsbHdnRCtFWVRpRU9zZWdFQTRKWks2aQ0KSS9qQlo5ODl4VFRCWm12S0xsRVBvWjlFS1ZNbmdwb3VYMFA2RHRkUHpHcUZIdjFiMEN3YkcvT2NXQWhDTFBSYg0KUXZVOWdzUWNheHhZZkJSUnV4QmN5VGU2aUZOTE9pelVub2I4RE9BZFFFVjNIS3gwVjMzQkNIcU1BckFpNVdmdQ0KaUpiUkZWOFhXS2EvZGVmWVNSYUVKMi9Gb2ZYUk91Y0hINHJMYXNDR3RHdUhuWkZZQ2ZIdUJ2V09ydVYrR2VHYw0KWVBBNHpRS0NBUUE0N0xvZ0dybGJvMnZNSk9XQlVhTHRtdXlmMmRiVHl0VmsrNCttWWZ3Qys5d2RwdHRSVDBsQQ0KeDNoRjduZ1lmMHczWUQxZG5rVnB1UVVwSk81V01HNDZLYzQ4Y1IrMEtyTG1VeERaazJMUzFnVWZvR2hjME0weA0KZUVDZ2UxM29ydU12TjVvN2hFUHUrNGthMTlJSUcvL0VkclVtbXNaZ2Mra2FEVmhld00rWWRYeXl0NzhRREE0Uw0KYk82MXZ6UXJUZjZ1Zm1HcGMzSmxjY3RESStPTnorSkFHRk8rN01URnowcTRtOVJYU3pJS2NxY0ZZbktxbHBFdw0KTWpDb1p6Qm9yaGpQWTJSZVYzT3QvWlBZMDVJWlpRcEpoUnFsNktHTDNuNXFxRFlWNlM5YlpEZWZHQWRRTmV3Tw0KVnRVdE8wZGo4M1VLK0RWSHRuMTJnZ0dZemdNSTNSOWhBb0lCQUVlalUzVFduTjNtY2FnTEFqRW96MjAzWFE4WQ0KRWd2K2pmY1oxK1RnY1hsRG44STl4NkdVQVFGOStZNnYzYlowU1JadFFxblRpSVM3K0c1K2dyaHZudkxtaGNoag0Kb3g1MVJCYnZTVFZZUktVcFRScktHMlhFSko3djZVQ25SaldyaEVqdkV1c0dmMmRRdlhhUmoyenJBVzlVSjVvKw0KeUlnSkNiTms0TGFTQnNXU3QzcmFNT1ZNK1BYeERmSGZqamRIZ0VubmUvMjdUbEk1RlFjSjNOellldlBiK2NFRA0KdTkrTUczWUNBbVhZK3ovajdJYUtJSXM1L05LVzY3aVRTRGNBb003dlRIYU5pMG11eDJJNFJLOUFoeTZiVUR1YQ0KZ2o3M2EzRWhjZnFzS1E1M3hXcmlvYXk5c0crVGRuaEJ3NWgzdDhFT2xBMWswL2RvZ0p6ejE1UHNFVFU9DQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: tls-secret
type: kubernetes.io/tls